### ISSUE TITLE
Selector hides all `footer` elements when printed

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk_template#279]
There's a CSS rule to hide the footer when printing, but it uses element selectors to determine what to hide:
https://github.com/alphagov/govuk_template/blob/master/source/assets/stylesheets/_core-print.scss#L76-L77

This assumes that all `footer` elements contain information that is not worth printing. That can't be guaranteed.

```css
body footer {
  display: none !important;
}
```
